### ISSUE TITLE
Server stop if IP connection is down 

### ISSUE THREAD

**Issue by Panda88CO** [simplextech/udi-poly-st-nuheat#2]
Seems node server stops (and does not recover) if IP connection goes down

**Comment by simplextech** [comment]
Last push should fix the issue with the uncaught exception when there's not internet and it tries to poll.

**Comment by Panda88CO** [comment]
it is still happening
[ST-NuHeat_9-8-2021_84235_PM.txt](https://github.com/simplextech/udi-poly-st-nuheat/files/7133234/ST-NuHeat_9-8-2021_84235_PM.txt)
